[build]
builder = "NIXPACKS"

[build.nixpacks]
aptPkgs = ["python3", "make", "g++"]

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
